# Example updated compose generated structure
version: '3.9'
services:
  python:
    build:
      context: ./apps/python
    container_name: sample-python
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
    networks:
      - app-net
  go:
    build:
      context: ./apps/go
    container_name: sample-go
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
