name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'package.json'
      - '.github/workflows/docs.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Remove node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json 
      - name: Install deps
        run: npm i
      - name: Build VitePress site
        env:
          VITEPRESS_BASE: /create-polyglot/
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
